### ISSUE TITLE
lv_examples build failing

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lv_examples#101]
`lv_examples`/`lv_sim_emscripten` are failing to build due to recent changes in LVGL which haven't been reflected in `lv_examples`.

https://github.com/lvgl/lv_examples/runs/2202515473

@kisvegabor Can you take a look?

**Comment by kisvegabor** [comment]
Fixed.

It's strange that I was not notified about the tests' failure.

**Comment by embeddedt** [comment]
This is a very old issue and the builds succeed now.
