### ISSUE TITLE
lv_demo_benchmark causes floating point exception

### ISSUE THREAD

**Issue by higaski** [lvgl/lv_examples#123]
The function rnd_next in the lv_demo_benchmark causes a floating point exception in [line 1007](https://github.com/lvgl/lv_demos/blob/1c0552beff27aee1cdc82ddd32340f4b9c1f1995/src/lv_demo_benchmark/lv_demo_benchmark.c#L1014) in case both input arguments are equal.

```c
static int32_t rnd_next(int32_t min, int32_t max)
{
    if(min > max) {
        int32_t t = min;
        min = max;
        max = t;
    }

    int32_t d = max - min;
    int32_t r = (rnd_map[rnd_act] % d) + min;  // Exception here

    rnd_act++;
    if(rnd_act >= RND_NUM) rnd_act = 0;

    return r;

}
```

**Comment by kisvegabor** [comment]
This case is handles here: https://github.com/lvgl/lv_demos/blob/1c0552beff27aee1cdc82ddd32340f4b9c1f1995/src/lv_demo_benchmark/lv_demo_benchmark.c#L1005
