### ISSUE TITLE
No cogwheel.c file

### ISSUE THREAD

**Issue by incity** [lvgl/lv_examples#55]
![image](https://user-images.githubusercontent.com/7846605/82972468-b3cd1a80-a007-11ea-803f-9f594332ddb5.png)

**Comment by kisvegabor** [comment]
Thanks!
I've updated the `mk` file to dynamically create the file list:
https://github.com/lvgl/lv_examples/commit/e5d7462bff9d7843cc904975532a1de86fc4a078#diff-fe5f36dadac046dccc83bc6eb6e1371d
