### ISSUE TITLE
long click the delete button cannot delete char in this keyboard screen

### ISSUE THREAD

**Issue by incity** [lvgl/lv_examples#58]
![image](https://user-images.githubusercontent.com/7846605/83231464-1bc56180-a1be-11ea-8bd2-2a628b5effea.png)

**Comment by kisvegabor** [comment]
It's working for me like this:
![kb](https://user-images.githubusercontent.com/7599318/83349478-70d7b380-a335-11ea-8656-f2f5836bfd2c.gif)

**Comment by embeddedt** [comment]
I was able to reproduce the issue. You have to be in numeric/symbols mode.

**Comment by embeddedt** [comment]
It should be fixed in https://github.com/lvgl/lvgl/commit/af812b0c55e8e45ca129f02112c872401e87a0e6 (use the `master` branch).

**Comment by incity** [comment]
> I was able to reproduce the issue. You have to be in numeric/symbols mode. I am working on a fix now.

yes

**Comment by incity** [comment]
> It should be fixed in [lvgl/lvgl@af812b0](https://github.com/lvgl/lvgl/commit/af812b0c55e8e45ca129f02112c872401e87a0e6) (use the `master` branch).

thank you
