### ISSUE TITLE
the lastest lv_demo_printer render effect of the four desktop items has problem.

### ISSUE THREAD

**Issue by incity** [lvgl/lv_examples#59]
[2020-06.zip](https://github.com/lvgl/lv_examples/files/4708992/2020-06.zip)

the new.mp4 is the lastest repo, the four desktop items' backgroud render is not smooth as the old one.

**Comment by incity** [comment]
the shadow part of the desktop item has a flash when do an animation.(windows switch)

**Comment by incity** [comment]
@kisvegabor could fix this?

**Comment by kisvegabor** [comment]
Thanks! On the video or in my simulator I can't see any difference. I can test in on hardware tomorrow.

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/83482957-1d4f9c00-a4d4-11ea-9b3b-6e786955d7ff.png)
you can stare at the place i pointed out

**Comment by incity** [comment]
![image](https://user-images.githubusercontent.com/7846605/83483029-4cfea400-a4d4-11ea-96ee-62f4b03fe2fd.png)

**Comment by incity** [comment]
seems has a background repaint?? 
![image](https://user-images.githubusercontent.com/7846605/83483144-90591280-a4d4-11ea-9f25-1993a77d685b.png)
the old one is like this.

**Comment by kisvegabor** [comment]
Oh, got it. I tried to speed up drawing of these large images but it introduced this issue.
I'll revert it tomorrow.

**Comment by kisvegabor** [comment]
I've pushed a fix into `master`.
