### ISSUE TITLE
list item delimiter not show

### ISSUE THREAD

**Issue by incity** [lvgl/lv_examples#61]
![image](https://user-images.githubusercontent.com/7846605/83492349-bcc95a80-a4e5-11ea-881c-7b1eb08aa38f.png)
need one line here

**Comment by embeddedt** [comment]
Looks like a possible invalidation issue (the spacer above "This is a quite long text" is too long and seems to ignore the padding).

**Comment by kisvegabor** [comment]
Actually it's an issue in the theme. The bottom thin line is painted to greenish when focused. But the checked button is also greenish so the line is not visible when a button is checked and focused (it's the lastly clicked).

I'm consulting with the graphics designer about how to highlight the focused button.

**Comment by kisvegabor** [comment]
Should be fixed in `lvgl/master`
