### ISSUE TITLE
Kconfig for lv_port_esp32 repo

### ISSUE THREAD

**Issue by C47D** [lvgl/lv_examples#66]
We're adding a Kconfig file to the lv_port_esp32 components and this repo is one of them, I'm wondering what should we add on the Kconfig configuration menu, here's what we were planning to add:

- Let the user choose what demo or example to run.
- Let the user enable or disable the task to 'emulate' user input, when available.

This changes will be first tested on the lv_port_esp32 repo and then added here when they are proven to work fine.

What do you think?

**Comment by kisvegabor** [comment]
I think all we need to do is exposing the content of [lv_ex_conf.h](https://github.com/lvgl/lv_examples/blob/master/lv_ex_conf_templ.h).
