### ISSUE TITLE
The sliding direction of tab Visuals is opposite

### ISSUE THREAD

**Issue by huqifj** [lvgl/lv_examples#69]
This demo on website https://lvgl.io/demos, when you scroll up or down

**Comment by embeddedt** [comment]
Are you referring to the mouse wheel or dragging the screen? The mouse wheel doesn't work at all in the demo (and I don't think it's expected to).

If you're referring to dragging the screen, it's simulating a touchscreen (like a phone), and the directions match how you would move your finger.

**Comment by huqifj** [comment]
Thanks for your reply.
I do this by dragging the scroll bar on the right side of the screen. Now I know it's simulating a mobile device. Thank you again
