### ISSUE TITLE
ERROR IN lv_img_set_src from bin file

### ISSUE THREAD

**Issue by zq190kg** [lvgl/lv_examples#74]
hi,I use the following code,An error occurred,maybe  《lv_fs_file_t * file_p》  Parameter transfer error
void test(void)
{
	lv_obj_t *img;
	img = lv_img_create(lv_scr_act(), NULL);
	lv_img_set_src(img, "c:/1.bin");
}
![bin1](https://user-images.githubusercontent.com/53965706/92984724-e0d20a00-f4de-11ea-969a-d905a0bcf96d.jpg)
![bin2](https://user-images.githubusercontent.com/53965706/92984728-e6c7eb00-f4de-11ea-9eee-a5541fae7382.jpg)
![bin3](https://user-images.githubusercontent.com/53965706/92984731-eb8c9f00-f4de-11ea-8da2-d16e6fa69d97.jpg)
but i used gif testcode,no error occurred;
void gif_demo(void)
{
lv_obj_t * img = lv_gif_create_from_file(lv_scr_act(), "c:/1.gif");
	              
}
![GIF](https://user-images.githubusercontent.com/53965706/92984740-1545c600-f4df-11ea-861e-d922329dd5e6.jpg)
![GIF1](https://user-images.githubusercontent.com/53965706/92984744-1a0a7a00-f4df-11ea-8593-4d34930e8ca7.jpg)

I USE LVGL "LV_EXAMPLES"&"LVGL_NEW_FS_API"&"lv_fs_if"&"lv_lib_gif"

**Comment by kisvegabor** [comment]
One thing I noticed that you should use uppercase letters as a driver.  I might mess up things internally.

**Comment by zq190kg** [comment]
the same test code in lvgl master is ok,     but  in lvgl new FS API branch is error.
I found a mistake in    ”lv_img_decoder_built_in_open” (lvgl new FS API branch)
![error1](https://user-images.githubusercontent.com/53965706/93071756-1cbdc880-f6b3-11ea-8f86-5af585db1894.jpg)

**Comment by zq190kg** [comment]
in  lvgl new FS API branch ,the lv_fs_file_t->drv parameters cannot be transmitted to  fs_seek  correctly

**Comment by zq190kg** [comment]
> One thing I noticed that you should use uppercase letters as a driver. I might mess up things internally.

I test uppercase letters as a driver，still error occurred in lvgl new FS API branch，but the lvgl master is ok，i think the Key points is not the uppercase,。Because I'm going to use GIF，so i must use   "LVGL_NEW_FS_API"&"lv_fs_if"&"lv_lib_gif"。

**Comment by kisvegabor** [comment]
Can you test this in `lv_img_decoder.c`?
```c
        user_data->f = f;
//        _lv_memcpy_small(user_data->f, &f, sizeof(f));
```

**Comment by zq190kg** [comment]
tks,user_data->f = f;  this ok
I tested “_lv_memcpy_small(user_data->f, f, sizeof(f));” before，not work

**Comment by kisvegabor** [comment]
I've fixed it.

**Comment by chliii** [comment]
HI,

Can you run the program now? 

I cant run the lv_lib_gif
