### ISSUE TITLE
 Call to lv_obj_refresh_style in lv_demo_printer_theme.c missing part argument

### ISSUE THREAD

**Issue by icodk** [lvgl/lv_examples#80]
Function lv_obj_refresh_style  requires now three arguments (only 2 in 7.1.0) but call to this function was not updated in
lv_demo_printer_theme.c 
Also the documentation only details two parameters, though the part parameter is in the function definition.

**Comment by kisvegabor** [comment]
Hi,

It's already fixed in the latest version. 
https://github.com/lvgl/lv_examples/blob/master/src/lv_demo_printer/lv_demo_printer_theme.c#L457

**Comment by kisvegabor** [comment]
As the issue should be fixed I close it.

If it's still not working as expected please comment here and reopen the issue.
